---

- name: deb822_repository dependencies
  apt:
    name: [
            'python3-debian',
          ]
    state: present

- name: mozillateam/ppa is enabled
  deb822_repository:
    name: mozillateam
    types: deb
    uris: https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x738BEB9321D1AAEC13EA9391AEBDF4819BE21867
    enabled: true
    state: present

- name: firefox snap not installed
  snap:
    name: [
            'firefox',
          ]
    state: absent

- name: firefox-esr is installed
  apt:
    name: [
            'firefox-esr',
          ]
    state: present

- name: touch screen for firefox is enabled
  lineinfile:
    path: /etc/environment
    regexp: 'MOZ_USE_XINPUT2=1'
    line: 'MOZ_USE_XINPUT2=1'

