---

- name: virtualbox guest additions installed
  apt:
    name: [
            'virtualbox-guest-x11',
          ]
    state: present

- name: add eduvm user to the vboxsf group
  command: usermod -a -G vboxsf eduvm
  register: vbgroup
  failed_when: vbgroup.rc != 0
  changed_when: False
