---

- name: memtest86+ not installed
  apt:
    name: [
            'memtest86+',
          ]
    state: absent

- name: fwupd not needed on VM
  apt:
    name: [
            'fwupd',
            'fwupd-signed',
          ]
    state: absent

- name: hplip not installed
  apt:
    name: [
            'hplip',
            'hplip-data',
          ]
    state: absent

- name: rfkill not installed
  apt:
    name: [
            'rfkill',
          ]
    state: absent

- name: sane not installed
  apt:
    name: [
            'sane-utils',
            'sane-airscan',
          ]
    state: absent

- name: xfce screensaver & power management removal as not needed on VM
  apt:
    name: [
            'xfce4-screensaver',
            'xfce4-power-manager',
            'xfce4-power-manager-data',
            'xfce4-power-manager-plugins',
          ]
    state: absent

- name: (x)ubuntu branding not installed
  apt:
    name: [
            'xubuntu-artwork',
            'xubuntu-docs',
            'xubuntu-wallpapers',
            'xubuntu-icon-theme',
            'plymouth-theme-xubuntu-logo',
            'plymouth-theme-xubuntu-text',
            'plymouth-theme-ubuntu-text',
            'ubiquity-slideshow-xubuntu',
            'debian-cd',
            'ldm-xubuntu-theme',
          ]
    state: absent

