---

- name: old dependency packages removed
  apt:
    autoremove: yes

- name: non installed packages configuration purged
  command: apt-get purge -y '~c'
  register: purge_config
  changed_when: "'The following packages will be REMOVED' in purge_config.stdout"

- name: apt cache is clean
  command: apt-get clean -y
  changed_when: False

- name: disabled snaps are removed
  command: bash -c 'snap list --all | grep disabled | while read snapname ver rev trk pub notes; do snap remove "$snapname" --revision="$rev";  done'
  register: disabled_snaps
  changed_when: "'removed' in disabled_snaps.stdout" 

