---

- name: deb822_repository dependencies
  apt:
    name: [
            'python3-debian',
          ]
    state: present

- name: omtt/ppa is enabled
  deb822_repository:
    name: omtt
    types: deb
    uris: https://ppa.launchpadcontent.net/chyla-org/omtt-plucky-puffin/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE95A625F7C660ECA7ECD4AAF14D87715B734E0F5
    enabled: true
    state: present

- name: omtt is installed
  apt:
    name: [
            'omtt',
          ]
    state: present

