---

- name: omtt/ppa is enabled
  apt_repository:
    repo: 'ppa:chyla-org/omtt-mantic'
    state: present

- name: omtt is installed
  apt:
    name: [
            'omtt',
          ]
    state: present

