---

- name: git is installed
  apt:
    name: [
            'git',
            'git-lfs',
            'git-man',
            'git-doc',
            'git-gui',
            'git-svn',
            'gitk',
          ]
    state: present

- name: svn is installed
  apt:
    name: [
            'subversion',
          ]
    state: present

